version: "3.8"
services:
  ktu-bot:
    image: devadathanmb/ktu-bot:latest   # Pull the latest image from Docker Hub
    platform: linux/arm64
    restart: always
    depends_on:
      redis-queue-db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .env
        target: /bot/.env

  redis-queue-db:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
